name 'kbe_role_ubuntu_1604_base'
maintainer 'Kyle Evans'
maintainer_email 'kylebe@gmail.com'
license 'all_rights'
description 'Installs/Configures kbe_role_ubuntu_1604_base'
long_description 'Installs/Configures kbe_role_ubuntu_1604_base'
version '0.1.0'
